### ISSUE TITLE
Error in output log

### ISSUE THREAD

**Issue by t1a2l** [algernon-A/Ploppable-RICO-Revisited#22] opened 2020-04-10 09:14 UTC
Realistic Population Revisited: 4x3_Beach Hotel2 attempted to be use CommercialTourist with level 1. Returning as level 0.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library E:/Program Files (x86)/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/libc
Fallback handler could not load library E:/Program Files (x86)/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/.\libc
Fallback handler could not load library E:/Program Files (x86)/Steam/steamapps/common/Cities_Skylines/Cities_Data/Mono/libc
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: E:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
Realistic Population Revisited: 4x3_Beach Hotel attempted to be use CommercialTourist with level 1. Returning as level 0.

**Comment by algernon-A** [comment] 2020-04-10 09:43
The message at the top is actually from Realistic Population Revisited, and is harmless (will be removed in the next update of that mod).

I've tried to reproduce this issue with this asset (vanilla 4x3_Beach Hotel2), Realistic Population Revisited, and Ploppable RICO Revisited (as well as a host of other mods) and have been unable to reproduce.

Can you please confirm that this is a consistent, reproduceable issue?  And if so, post your full output_log.txt?

**Comment by t1a2l** [comment] 2020-04-10 10:04
[output_log.txt](https://github.com/algernon-A/Ploppable-RICO-Revisited/files/4461031/output_log.txt)
@algernon-A

**Comment by algernon-A** [comment] 2020-04-10 10:25
What was the symptom?  Did the game crash?  And does the symptom happen every time you play the game, or just once?

**Comment by t1a2l** [comment] 2020-04-10 10:29
The game don't crash, I recieve this error I think from before your version. It is from the original version of the rico mod. I just geeting it in the log file every time. I am not sure it is connected to your mod, maybe your mod is just around it and it is not connected at all. Is there a way to retrace the issue?

**Comment by algernon-A** [comment] 2020-04-10 12:03
It's a known issue, and harmless (other than logging messages).

Closing as duplicate of #17.

**Closed as completed by algernon-A** 2020-04-10 12:03 UTC
Labels: duplicate
