### ISSUE TITLE
Broken instruments panel in Editor

### ISSUE THREAD

**Issue by Dushess** [algernon-A/Ploppable-RICO-Revisited#21] opened 2020-04-08 10:35 UTC
Even with your updated version i see this. Reported also by few players before.
https://steamcommunity.com/sharedfiles/filedetails/?id=2052848155
Main panel and Asset settings panel seems to be affected.

[output_log.txt](https://github.com/algernon-A/Ploppable-RICO-Revisited/files/4449923/output_log.txt)
Yes, there is lots of assets, many notifications about small problems lite names and LODs stats.

**Comment by algernon-A** [comment] 2020-04-10 10:04
I have tested and have been unable to reproduce this issue; the asset editor is working fine for me with this mod enabled.

However, I notice from the log you've attached that you're running at least several out-of-date mods that should no longer be used, and some of which are known to affect the asset editor.

In particular, I noticed Klyte Commons and Network Skins 1 - remove them and update your Klyte and Network Skins mods to the latest versions.

You're also using the SeniorCitizenCenterMod which is outdated and broken, along with all the assets that use it.

There may be more, but I didn't go any further as it's clear that your mod collection isn't up-to-date.  Remember that mod collections aren't "click-and-forget" but require occasional active management.  Please review and update all your mods; use this to help: https://docs.google.com/spreadsheets/d/1mVFkj_7ij4FLzKs2QJaONNmb9Z-SRqUeG6xFGqEX1ew/edit#gid=1253301438.

Closing this issue as not caused by this mod, but by one of the other broken and outdated mods used by the OP.

Please feel free to open a new issue if you can confirm that there is a reproducible bug with this mod alone (note that doing so does require disabling ALL other mods to confirm that this is the one causing the problem).

**Closed as completed by algernon-A** 2020-04-10 10:04 UTC

**Comment by Dushess** [comment] 2020-04-13 06:57
SCM is removed for now (maybe new vanilla feature is the same) NS1 is removed long ago, i nave 2nd version now. Commons surely not needed anymore, going to test. And ain't they can in autoupdating? Yes, my modpack is MOSTLY up to date, wish it to be completely, but....
